#!/usr/bin/env ruby

require_relative 'git_utils.rb'

def install_utilities
  `gem install bundler`
  `bundle install`
end

def configure_remote
  run_git_command('remote rm jp')
  run_git_command('remote add jp git://github.com/sydneyjune2013/app.git')
end

def create_first_branches
  %w[clean starting_point].each do |branch| 
    checkout 'master'
    checkout(branch)
  end
end

install_utilities
configure_remote
create_first_branches
